image: golang:latest

variables:
  REPO_NAME: gitlab.papegames.com/fengche/yayagf

before_script:
  - echo $CI_PROJECT_DIR
  - export GOPATH=/home/gitlab-runner
  - export PATH=$PATH:/usr/local/go/bin

stages:
  - test
  - build

format:
  stage: test
  script:
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race -cover -coverprofile=./coverage.data $(go list ./... | grep -v /vendor/)
    - go tool cover -html=./coverage.data -o ./coverage.html
  artifacts:
    untracked: true

#lint_code:
#  stage: test
#  script:
#    - golangci-lint run ./...

sonar_analyze:
  stage: test
  only:
    refs:
      - master
  script:
    - wget http://192.168.0.97:8000/sonar-scanner.tar.gz
    - tar -xvf sonar-scanner.tar.gz
    - |
    ./sonar-scanner/bin/sonar-scanner \
      -Dsonar.host.url=http://192.168.0.97:9000 \
      -Dsonar.sources=. \
      -Dsonar.projectKey=$CI_PROJECT_NAME \
      -Dsonar.login=dced6e70e45d30783fda260701e8e0169b61013f \
      -Dsonar.tests=. \
      -Dsonar.exclusions=**/*_test.go,**/vendor/**\
      -Dsonar.test.inclusions=**/*_test.go\
      -Dsonar.test.exclusions=**/vendor/**

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/nnmutex
  artifacts:
    paths:
      - nnmutex
