image: golang:1.13

variables:
  REPO_NAME: gitlab.papegames.com/fengche/yayagf

before_script:
  - echo $CI_PROJECT_DIR
  - export GOPATH=/home/gitlab-runner
  - export PATH=$PATH:/usr/local/go/bin

stages:
  - test
  - build

sonar_analyze:
  stage: test
  only:
    refs:
      - master
  script:
    - wget http://192.168.0.97:8000/sonar-scanner.tar.gz
    - tar -xvf sonar-scanner.tar.gz
    - go test -race -cover -v ./... -json -coverprofile=covprofile > test.json
    - go vet -n ./... 2> report.out
    - golangci-lint run ./... --out-format=checkstyle > golangci-lint-report.xml || true
    - "./sonar-scanner/bin/sonar-scanner \
      -Dsonar.host.url=http://192.168.0.97:9000 \
      -Dsonar.sources=. \
      -Dsonar.projectKey=$CI_PROJECT_NAME \
      -Dsonar.login=dced6e70e45d30783fda260701e8e0169b61013f \
      -Dsonar.tests=. \
      -Dsonar.exclusions=**/*_test.go,**/vendor/** \
      -Dsonar.go.tests.reportPaths=test.json \
      -Dsonar.go.coverage.reportPaths=covprofile \
      -Dsonar.go.govet.reportPaths=report.out \
      -Dsonar.go.golangci-lint.reportPaths=golangci-lint-report.xml \
      -Dsonar.test.inclusions=**/*_test.go \
      -Dsonar.test.exclusions=**/vendor/**"
