
pipeline {
    agent any
    tools {
        go 'Go 1.14'
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    try {
                        switch(gitlabActionType) {
                        case "PUSH":
                            echo "repo: ${gitlabSourceRepoHomepage} user: ${gitlabUserName} action: ${gitlabActionType} before: ${gitlabBefore} after: ${gitlabAfter}"
                            sh "git checkout ${gitlabAfter}"
                            break
                        case "TAG_PUSH":
                            echo "repo: ${gitlabSourceRepoHomepage} user: ${gitlabUserName} action: ${gitlabActionType} before: ${gitlabBefore} after: ${gitlabAfter}"
                            sh "git checkout ${gitlabAfter}"
                            break
                        default:
                            echo gitlabActionType
                        }
                    } catch (Exception ex){
                        gitlabActionType = "push by hand"
                    }
                }
            }
        }

        stage('Build') {
            steps {
                sh 'GOPROXY=https://goproxy.io GOSUMDB=off GOPRIVATE=gitlab.papegames.com/* go build -a -o a'
            }
            post {
                failure {
		    dingtalk (
			robot: '06f37cd7-c5ad-41b4-8042-b96ddb6c0992',
			type: 'MARKDOWN',
			at: ["15921542429"],
			title: 'build failure',
			text: ["TDS a测试环境 构建失败"],
		    )
                }
                fixed {
		    dingtalk (
			robot: '06f37cd7-c5ad-41b4-8042-b96ddb6c0992',
			type: 'MARKDOWN',
			at: ["15921542429"],
			title: 'build failure',
			text: ["TDS a测试环境 构建又好了"],
		    )
                }
            }
        }

        stage('Stage') {
            when{ not {equals actual: gitlabActionType, expected: "TAG_PUSH"} }
            steps {
            	sh 'ssh root@101.37.25.45 "mkdir -p /data/tds/a"'
            	sh 'ssh root@101.37.25.45 "screen -S a -X quit" || true'
                sh 'scp ./a root@101.37.25.45:/data/tds/a/'
                sh "JENKINS_NODE_COOKIE=dontKillMe ssh root@101.37.25.45 \"cd /data/tds/a; screen -dmS a bash -c \\\"./a 1>>/data/tds/logs/a.log 2>>/data/tds/logs/a.log \\\"\""
            }
            post {
                failure {
		    dingtalk (
			robot: '06f37cd7-c5ad-41b4-8042-b96ddb6c0992',
			type: 'MARKDOWN',
			at: ["15921542429"],
			title: 'build failure',
			text: ["TDS a测试环境 部署失败"],
		    )
                }
                fixed {
		    dingtalk (
			robot: '06f37cd7-c5ad-41b4-8042-b96ddb6c0992',
			type: 'MARKDOWN',
			at: ["15921542429"],
			title: 'build failure',
			text: ["TDS a测试环境 部署又好了"],
		    )
                }
            }
        }

        stage('Package') {
            when{ equals actual: gitlabActionType, expected: "TAG_PUSH" }
            steps {
                script {
                     tag = sh(script: "git tag --points-at ${gitlabAfter}", returnStdout: true).trim()
                     if (tag==""){
                     	throw "no tag"
                     }
                     now = sh(returnStdout: true, script: "date '+%Y-%m-%d-%H-%M-%S'").trim()
                     fname = "a-${tag}_${now}.tar.gz"
                     sh("tar -czf ${fname} a")
                     sh "scp ${fname} admin@192.168.0.11:/volume1/SDK/tds/"
		             md5 = sh(script: "md5sum ${fname}", returnStdout: true).trim()
                }
            }
            post {
                success {
		    dingtalk (
			robot: '06f37cd7-c5ad-41b4-8042-b96ddb6c0992',
			type: 'MARKDOWN',
			at: ["15921542429"],
			title: 'TDS a Tag Done',
			text: ["TDS a最新tag: ${tag}, md5: ${md5}"],
		    )
                }
                failure {
		    dingtalk (
			robot: '06f37cd7-c5ad-41b4-8042-b96ddb6c0992',
			type: 'MARKDOWN',
			at: ["15921542429"],
			title: 'TDS a Tag Failure',
			text: ["TDS a ${tag} 打包失败"],
		    )
                }
            }
        }
        stage('Clean') {
            steps {
                cleanWs()
            }
        }
    }
}
