// Code generated by entc, DO NOT EDIT.

package a

import (
	"github.com/facebook/ent/dialect/sql"
	"test.com/testdata/app/crud/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// A applies equality check predicate on the "a" field. It's identical to AEQ.
func A(v int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldA), v))
	})
}

// AEQ applies the EQ predicate on the "a" field.
func AEQ(v int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldA), v))
	})
}

// ANEQ applies the NEQ predicate on the "a" field.
func ANEQ(v int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldA), v))
	})
}

// AIn applies the In predicate on the "a" field.
func AIn(vs ...int) predicate.A {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.A(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldA), v...))
	})
}

// ANotIn applies the NotIn predicate on the "a" field.
func ANotIn(vs ...int) predicate.A {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.A(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldA), v...))
	})
}

// AGT applies the GT predicate on the "a" field.
func AGT(v int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldA), v))
	})
}

// AGTE applies the GTE predicate on the "a" field.
func AGTE(v int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldA), v))
	})
}

// ALT applies the LT predicate on the "a" field.
func ALT(v int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldA), v))
	})
}

// ALTE applies the LTE predicate on the "a" field.
func ALTE(v int) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldA), v))
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.A) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.A) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.A) predicate.A {
	return predicate.A(func(s *sql.Selector) {
		p(s.Not())
	})
}
