// Code generated by entc, DO NOT EDIT.

package crud

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"test.com/testdata/app/crud/a"
)

// A is the model entity for the A schema.
type A struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// A holds the value of the "a" field.
	A int `json:"a,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*A) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case a.FieldID, a.FieldA:
			values[i] = &sql.NullInt64{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type A", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the A fields.
func (a *A) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case a.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case a.FieldA:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field a", values[i])
			} else if value.Valid {
				a.A = int(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this A.
// Note that you need to call A.Unwrap() before calling this method if this A
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *A) Update() *AUpdateOne {
	return (&AClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the A entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *A) Unwrap() *A {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("crud: A is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *A) String() string {
	var builder strings.Builder
	builder.WriteString("A(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteString(", a=")
	builder.WriteString(fmt.Sprintf("%v", a.A))
	builder.WriteByte(')')
	return builder.String()
}

// As is a parsable slice of A.
type As []*A

func (a As) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
