// Code generated by entc, DO NOT EDIT.

package crud

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"test.com/testdata/app/crud/a"
	"test.com/testdata/app/crud/predicate"
)

// AQuery is the builder for querying A entities.
type AQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.A
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AQuery builder.
func (a *AQuery) Where(ps ...predicate.A) *AQuery {
	a.predicates = append(a.predicates, ps...)
	return a
}

// Limit adds a limit step to the query.
func (a *AQuery) Limit(limit int) *AQuery {
	a.limit = &limit
	return a
}

// Offset adds an offset step to the query.
func (a *AQuery) Offset(offset int) *AQuery {
	a.offset = &offset
	return a
}

// Order adds an order step to the query.
func (a *AQuery) Order(o ...OrderFunc) *AQuery {
	a.order = append(a.order, o...)
	return a
}

// First returns the first A entity from the query.
// Returns a *NotFoundError when no A was found.
func (a *AQuery) First(ctx context.Context) (*A, error) {
	nodes, err := a.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{a.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (a *AQuery) FirstX(ctx context.Context) *A {
	node, err := a.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first A ID from the query.
// Returns a *NotFoundError when no A ID was found.
func (a *AQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = a.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{a.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (a *AQuery) FirstIDX(ctx context.Context) int {
	id, err := a.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single A entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one A entity is not found.
// Returns a *NotFoundError when no A entities are found.
func (a *AQuery) Only(ctx context.Context) (*A, error) {
	nodes, err := a.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{a.Label}
	default:
		return nil, &NotSingularError{a.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (a *AQuery) OnlyX(ctx context.Context) *A {
	node, err := a.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only A ID in the query.
// Returns a *NotSingularError when exactly one A ID is not found.
// Returns a *NotFoundError when no entities are found.
func (a *AQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = a.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{a.Label}
	default:
		err = &NotSingularError{a.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (a *AQuery) OnlyIDX(ctx context.Context) int {
	id, err := a.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of As.
func (a *AQuery) All(ctx context.Context) ([]*A, error) {
	if err := a.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return a.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (a *AQuery) AllX(ctx context.Context) []*A {
	nodes, err := a.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of A IDs.
func (a *AQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := a.Select(a.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (a *AQuery) IDsX(ctx context.Context) []int {
	ids, err := a.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (a *AQuery) Count(ctx context.Context) (int, error) {
	if err := a.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return a.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (a *AQuery) CountX(ctx context.Context) int {
	count, err := a.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (a *AQuery) Exist(ctx context.Context) (bool, error) {
	if err := a.prepareQuery(ctx); err != nil {
		return false, err
	}
	return a.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (a *AQuery) ExistX(ctx context.Context) bool {
	exist, err := a.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (a *AQuery) Clone() *AQuery {
	if a == nil {
		return nil
	}
	return &AQuery{
		config:     a.config,
		limit:      a.limit,
		offset:     a.offset,
		order:      append([]OrderFunc{}, a.order...),
		predicates: append([]predicate.A{}, a.predicates...),
		// clone intermediate query.
		sql:  a.sql.Clone(),
		path: a.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		A int `json:"a,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.A.Query().
//		GroupBy(a.FieldA).
//		Aggregate(crud.Count()).
//		Scan(ctx, &v)
//
func (a *AQuery) GroupBy(field string, fields ...string) *AGroupBy {
	group := &AGroupBy{config: a.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := a.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return a.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		A int `json:"a,omitempty"`
//	}
//
//	client.A.Query().
//		Select(a.FieldA).
//		Scan(ctx, &v)
//
func (a *AQuery) Select(field string, fields ...string) *ASelect {
	a.fields = append([]string{field}, fields...)
	return &ASelect{AQuery: a}
}

func (a *AQuery) prepareQuery(ctx context.Context) error {
	for _, f := range a.fields {
		if !a.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("crud: invalid field %q for query", f)}
		}
	}
	if a.path != nil {
		prev, err := a.path(ctx)
		if err != nil {
			return err
		}
		a.sql = prev
	}
	return nil
}

func (a *AQuery) sqlAll(ctx context.Context) ([]*A, error) {
	var (
		nodes = []*A{}
		_spec = a.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &A{config: a.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("crud: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, a.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (a *AQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := a.querySpec()
	return sqlgraph.CountNodes(ctx, a.driver, _spec)
}

func (a *AQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := a.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("crud: check existence: %v", err)
	}
	return n > 0, nil
}

func (a *AQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   a.Table,
			Columns: a.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: a.FieldID,
			},
		},
		From:   a.sql,
		Unique: true,
	}
	if fields := a.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, a.FieldID)
		for i := range fields {
			if fields[i] != a.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := a.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := a.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := a.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := a.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, a.ValidColumn)
			}
		}
	}
	return _spec
}

func (a *AQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(a.driver.Dialect())
	t1 := builder.Table(a.Table)
	selector := builder.Select(t1.Columns(a.Columns...)...).From(t1)
	if a.sql != nil {
		selector = a.sql
		selector.Select(selector.Columns(a.Columns...)...)
	}
	for _, p := range a.predicates {
		p(selector)
	}
	for _, p := range a.order {
		p(selector, a.ValidColumn)
	}
	if offset := a.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := a.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AGroupBy is the group-by builder for A entities.
type AGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ab *AGroupBy) Aggregate(fns ...AggregateFunc) *AGroupBy {
	ab.fns = append(ab.fns, fns...)
	return ab
}

// Scan applies the group-by query and scans the result into the given value.
func (ab *AGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ab.path(ctx)
	if err != nil {
		return err
	}
	ab.sql = query
	return ab.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ab *AGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ab.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ab *AGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ab.fields) > 1 {
		return nil, errors.New("crud: AGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ab.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ab *AGroupBy) StringsX(ctx context.Context) []string {
	v, err := ab.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ab *AGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ab.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{a.Label}
	default:
		err = fmt.Errorf("crud: AGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ab *AGroupBy) StringX(ctx context.Context) string {
	v, err := ab.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ab *AGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ab.fields) > 1 {
		return nil, errors.New("crud: AGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ab.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ab *AGroupBy) IntsX(ctx context.Context) []int {
	v, err := ab.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ab *AGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ab.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{a.Label}
	default:
		err = fmt.Errorf("crud: AGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ab *AGroupBy) IntX(ctx context.Context) int {
	v, err := ab.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ab *AGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ab.fields) > 1 {
		return nil, errors.New("crud: AGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ab.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ab *AGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ab.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ab *AGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ab.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{a.Label}
	default:
		err = fmt.Errorf("crud: AGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ab *AGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ab.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ab *AGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ab.fields) > 1 {
		return nil, errors.New("crud: AGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ab.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ab *AGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ab.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ab *AGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ab.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{a.Label}
	default:
		err = fmt.Errorf("crud: AGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ab *AGroupBy) BoolX(ctx context.Context) bool {
	v, err := ab.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ab *AGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ab.fields {
		if !a.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ab.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ab.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ab *AGroupBy) sqlQuery() *sql.Selector {
	selector := ab.sql
	columns := make([]string, 0, len(ab.fields)+len(ab.fns))
	columns = append(columns, ab.fields...)
	for _, fn := range ab.fns {
		columns = append(columns, fn(selector, a.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(ab.fields...)
}

// ASelect is the builder for selecting fields of A entities.
type ASelect struct {
	*AQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (a *ASelect) Scan(ctx context.Context, v interface{}) error {
	if err := a.prepareQuery(ctx); err != nil {
		return err
	}
	a.sql = a.AQuery.sqlQuery(ctx)
	return a.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (a *ASelect) ScanX(ctx context.Context, v interface{}) {
	if err := a.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (a *ASelect) Strings(ctx context.Context) ([]string, error) {
	if len(a.fields) > 1 {
		return nil, errors.New("crud: ASelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := a.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (a *ASelect) StringsX(ctx context.Context) []string {
	v, err := a.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (a *ASelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = a.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{a.Label}
	default:
		err = fmt.Errorf("crud: ASelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (a *ASelect) StringX(ctx context.Context) string {
	v, err := a.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (a *ASelect) Ints(ctx context.Context) ([]int, error) {
	if len(a.fields) > 1 {
		return nil, errors.New("crud: ASelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := a.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (a *ASelect) IntsX(ctx context.Context) []int {
	v, err := a.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (a *ASelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = a.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{a.Label}
	default:
		err = fmt.Errorf("crud: ASelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (a *ASelect) IntX(ctx context.Context) int {
	v, err := a.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (a *ASelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(a.fields) > 1 {
		return nil, errors.New("crud: ASelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := a.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (a *ASelect) Float64sX(ctx context.Context) []float64 {
	v, err := a.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (a *ASelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = a.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{a.Label}
	default:
		err = fmt.Errorf("crud: ASelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (a *ASelect) Float64X(ctx context.Context) float64 {
	v, err := a.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (a *ASelect) Bools(ctx context.Context) ([]bool, error) {
	if len(a.fields) > 1 {
		return nil, errors.New("crud: ASelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := a.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (a *ASelect) BoolsX(ctx context.Context) []bool {
	v, err := a.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (a *ASelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = a.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{a.Label}
	default:
		err = fmt.Errorf("crud: ASelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (a *ASelect) BoolX(ctx context.Context) bool {
	v, err := a.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (a *ASelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := a.sqlQuery().Query()
	if err := a.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (a *ASelect) sqlQuery() sql.Querier {
	selector := a.sql
	selector.Select(selector.Columns(a.fields...)...)
	return selector
}
