// Code generated by entc, DO NOT EDIT.

package crud

import (
	"context"
	"fmt"
	"log"

	"test.com/testdata/app/crud/migrate"

	"test.com/testdata/app/crud/a"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// A is the client for interacting with the A builders.
	A *AClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.A = NewAClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("crud: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("crud: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		A:      NewAClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		A:      NewAClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		A.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.A.Use(hooks...)
}

// AClient is a client for the A schema.
type AClient struct {
	config
}

// NewAClient returns a client for the A from the given config.
func NewAClient(c config) *AClient {
	return &AClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `a.Hooks(f(g(h())))`.
func (c *AClient) Use(hooks ...Hook) {
	c.hooks.A = append(c.hooks.A, hooks...)
}

// Create returns a create builder for A.
func (c *AClient) Create() *ACreate {
	mutation := newAMutation(c.config, OpCreate)
	return &ACreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of A entities.
func (c *AClient) CreateBulk(builders ...*ACreate) *ACreateBulk {
	return &ACreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for A.
func (c *AClient) Update() *AUpdate {
	mutation := newAMutation(c.config, OpUpdate)
	return &AUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AClient) UpdateOne(a *A) *AUpdateOne {
	mutation := newAMutation(c.config, OpUpdateOne, withA(a))
	return &AUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AClient) UpdateOneID(id int) *AUpdateOne {
	mutation := newAMutation(c.config, OpUpdateOne, withAID(id))
	return &AUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for A.
func (c *AClient) Delete() *ADelete {
	mutation := newAMutation(c.config, OpDelete)
	return &ADelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AClient) DeleteOne(a *A) *ADeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AClient) DeleteOneID(id int) *ADeleteOne {
	builder := c.Delete().Where(a.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ADeleteOne{builder}
}

// Query returns a query builder for A.
func (c *AClient) Query() *AQuery {
	return &AQuery{config: c.config}
}

// Get returns a A entity by its id.
func (c *AClient) Get(ctx context.Context, id int) (*A, error) {
	return c.Query().Where(a.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AClient) GetX(ctx context.Context, id int) *A {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AClient) Hooks() []Hook {
	return c.hooks.A
}
