// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// AsColumns holds the columns for the "as" table.
	AsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "a", Type: field.TypeInt},
	}
	// AsTable holds the schema information for the "as" table.
	AsTable = &schema.Table{
		Name:        "as",
		Columns:     AsColumns,
		PrimaryKey:  []*schema.Column{AsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AsTable,
	}
)

func init() {
}
